// Package store is the transaction boundary and the vocabulary around it.
//
// It is not a repository layer. Every query in this application is generated by
// sqlc from the SQL in db/queries, checked at build time against the schema in
// db/migrations, and callers run those generated functions directly against the
// pool that main created and injected. There are no methods here restating
// them: a method whose body is one generated call and an error wrap is a
// liability with nothing to show for it.
//
// What is left is what the generator does not do.
//
// InTx is the transaction lifecycle. sqlc gives Queries a WithTx that binds it
// to a pgx.Tx but says nothing about where the transaction comes from or when
// it commits, because that is the application's decision. This is that decision,
// in one place: every write opens a transaction, including the single-statement
// ones Postgres would make atomic anyway, so that "a write is a transaction" is
// a rule a reader verifies by looking rather than one that quietly stops being
// true when someone adds a second statement.
//
// MapError is the vocabulary. pgx.ErrNoRows and SQLSTATE 23505 are facts about
// Postgres; ErrNotFound and ErrConflict are facts about this application.
//
// Multi-tenancy is two layers deep -- an organization may contain many
// accounts, and the account is the unit of isolation -- so every tenant-owned
// query filters on both. Scope carries the pair so that a function signature
// cannot take them apart. It is validated where one is created, from a token in
// the auth middleware and at the entry to each workflow, and not again on every
// query: every action needs both halves, so one check at the top says what a
// check on each query would say, and says it sooner.
package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/dbiderman/identityhub/backend/internal/store/sqlcgen"
)

// ErrNotFound is returned when a lookup matches no row. Callers must not be
// able to distinguish "does not exist" from "belongs to another account".
var ErrNotFound = errors.New("no such record in this account")

// ErrConflict is returned when a write violates a uniqueness constraint.
var ErrConflict = errors.New("record already exists")

// Scope is the tenancy of a request: which organization, and which account
// within it. Every tenant-owned query filters on both.
type Scope struct {
	OrgID     uuid.UUID
	AccountID uuid.UUID
}

// Validate reports whether the scope identifies a real tenancy.
//
// It is called where a Scope is created -- the auth middleware, and the entry
// to each workflow -- and not on every query.
func (s Scope) Validate() error {
	if s.OrgID == uuid.Nil {
		return fmt.Errorf("scope is missing an organization")
	}
	if s.AccountID == uuid.Nil {
		return fmt.Errorf("scope is missing an account")
	}
	return nil
}

// String renders the scope for audit metadata and encryption binding. It
// contains no secret.
func (s Scope) String() string { return s.OrgID.String() + "/" + s.AccountID.String() }

// OpenPool connects to Postgres and verifies the connection is usable.
//
// One pool per process, created by main and injected. Nothing else opens one.
func OpenPool(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("parse the database connection string: %w", err)
	}
	cfg.MaxConns = 10
	cfg.MaxConnLifetime = time.Hour
	cfg.HealthCheckPeriod = 30 * time.Second

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("connect to the database: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("reach the database: %w", err)
	}
	return pool, nil
}

// Read returns the generated queries bound to the pool, for statements that
// only select.
//
// A read needs no transaction: one SELECT is consistent by itself, and wrapping
// it would cost two round trips to say nothing. Queries holds a single
// interface field, so this allocates nothing worth counting.
func Read(pool *pgxpool.Pool) *sqlcgen.Queries { return sqlcgen.New(pool) }

// InTx runs fn against queries bound to a new transaction on pool.
//
// This is the only place a transaction is opened. fn's statements all commit or
// none do, which is what replacing a connection and claiming an idempotency key
// depend on -- and what a single-statement write gets for free, so that adding
// a second statement to one later needs no thought.
func InTx(ctx context.Context, pool *pgxpool.Pool, fn func(*sqlcgen.Queries) error) error {
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin a transaction: %w", err)
	}
	// Rollback after a successful commit is a no-op, so this needs no flag.
	defer func() { _ = tx.Rollback(ctx) }()

	// WithTx is sqlc's own way to rebind a querier: same generated methods,
	// running on the transaction instead of the pool.
	if err := fn(Read(pool).WithTx(tx)); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit a transaction: %w", err)
	}
	return nil
}

// MapError translates a driver error into this application's vocabulary.
//
// A caller that cares whether a row was missing wraps its error in this; one
// that does not, does not. Everything else passes through unchanged.
func MapError(err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrNotFound
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" { // unique_violation
		return ErrConflict
	}
	return err
}

// NullableUUID maps the zero UUID to SQL NULL.
//
// Several columns hold an optional identifier -- an audit event's actor, a
// ticket's connection -- and none of them has a row with the zero UUID. Writing
// it produces a value that looks real and resolves to nobody, so there is one
// helper and every caller uses it.
func NullableUUID(id uuid.UUID) *uuid.UUID {
	if id == uuid.Nil {
		return nil
	}
	return &id
}
