// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuditEventActorType.
const (
	ApiKey AuditEventActorType = "api_key"
	System AuditEventActorType = "system"
	User   AuditEventActorType = "user"
)

// Valid indicates whether the value is a known member of the AuditEventActorType enum.
func (e AuditEventActorType) Valid() bool {
	switch e {
	case ApiKey:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionStatus.
const (
	Active  ConnectionStatus = "active"
	Invalid ConnectionStatus = "invalid"
	Revoked ConnectionStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ConnectionStatus enum.
func (e ConnectionStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Invalid:
		return true
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for FailureCode.
const (
	FailureCodeConflict                 FailureCode = "conflict"
	FailureCodeConnectionUnusable       FailureCode = "connection_unusable"
	FailureCodeCredentialRejected       FailureCode = "credential_rejected"
	FailureCodeForbidden                FailureCode = "forbidden"
	FailureCodeIdempotencyKeyInProgress FailureCode = "idempotency_key_in_progress"
	FailureCodeIdempotencyKeyReused     FailureCode = "idempotency_key_reused"
	FailureCodeInternalError            FailureCode = "internal_error"
	FailureCodeMalformedRequest         FailureCode = "malformed_request"
	FailureCodeNotConnected             FailureCode = "not_connected"
	FailureCodeNotFound                 FailureCode = "not_found"
	FailureCodeProviderNotFound         FailureCode = "provider_not_found"
	FailureCodeProviderRateLimited      FailureCode = "provider_rate_limited"
	FailureCodeProviderRejected         FailureCode = "provider_rejected"
	FailureCodeProviderUnavailable      FailureCode = "provider_unavailable"
	FailureCodeQueueUnavailable         FailureCode = "queue_unavailable"
	FailureCodeUnauthorized             FailureCode = "unauthorized"
	FailureCodeUnsupportedOperation     FailureCode = "unsupported_operation"
	FailureCodeValidationFailed         FailureCode = "validation_failed"
)

// Valid indicates whether the value is a known member of the FailureCode enum.
func (e FailureCode) Valid() bool {
	switch e {
	case FailureCodeConflict:
		return true
	case FailureCodeConnectionUnusable:
		return true
	case FailureCodeCredentialRejected:
		return true
	case FailureCodeForbidden:
		return true
	case FailureCodeIdempotencyKeyInProgress:
		return true
	case FailureCodeIdempotencyKeyReused:
		return true
	case FailureCodeInternalError:
		return true
	case FailureCodeMalformedRequest:
		return true
	case FailureCodeNotConnected:
		return true
	case FailureCodeNotFound:
		return true
	case FailureCodeProviderNotFound:
		return true
	case FailureCodeProviderRateLimited:
		return true
	case FailureCodeProviderRejected:
		return true
	case FailureCodeProviderUnavailable:
		return true
	case FailureCodeQueueUnavailable:
		return true
	case FailureCodeUnauthorized:
		return true
	case FailureCodeUnsupportedOperation:
		return true
	case FailureCodeValidationFailed:
		return true
	default:
		return false
	}
}

// Defines values for FieldKind.
const (
	Email  FieldKind = "email"
	Secret FieldKind = "secret"
	Text   FieldKind = "text"
	Url    FieldKind = "url"
)

// Valid indicates whether the value is a known member of the FieldKind enum.
func (e FieldKind) Valid() bool {
	switch e {
	case Email:
		return true
	case Secret:
		return true
	case Text:
		return true
	case Url:
		return true
	default:
		return false
	}
}

// Defines values for FiledTicketSource.
const (
	FiledTicketSourceApi        FiledTicketSource = "api"
	FiledTicketSourceAutomation FiledTicketSource = "automation"
	FiledTicketSourceUi         FiledTicketSource = "ui"
)

// Valid indicates whether the value is a known member of the FiledTicketSource enum.
func (e FiledTicketSource) Valid() bool {
	switch e {
	case FiledTicketSourceApi:
		return true
	case FiledTicketSourceAutomation:
		return true
	case FiledTicketSourceUi:
		return true
	default:
		return false
	}
}

// Defines values for MeRoles.
const (
	Admin  MeRoles = "admin"
	Member MeRoles = "member"
)

// Valid indicates whether the value is a known member of the MeRoles enum.
func (e MeRoles) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}

// Defines values for PendingTicketStatus.
const (
	Pending PendingTicketStatus = "pending"
)

// Valid indicates whether the value is a known member of the PendingTicketStatus enum.
func (e PendingTicketStatus) Valid() bool {
	switch e {
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for SignInTokenType.
const (
	Bearer SignInTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SignInTokenType enum.
func (e SignInTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for TicketSource.
const (
	TicketSourceApi        TicketSource = "api"
	TicketSourceAutomation TicketSource = "automation"
	TicketSourceUi         TicketSource = "ui"
)

// Valid indicates whether the value is a known member of the TicketSource enum.
func (e TicketSource) Valid() bool {
	switch e {
	case TicketSourceApi:
		return true
	case TicketSourceAutomation:
		return true
	case TicketSourceUi:
		return true
	default:
		return false
	}
}

// APIKey defines model for APIKey.
type APIKey struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// KeyId The public half.
	KeyId string `json:"keyId"`

	// LastUsedAt Never used is a non-human identity worth retiring.
	LastUsedAt nullable.Nullable[time.Time] `json:"lastUsedAt,omitempty"`
	Name       string                       `json:"name"`
	RevokedAt  nullable.Nullable[time.Time] `json:"revokedAt,omitempty"`
	Scopes     []string                     `json:"scopes"`
}

// APIKeyList defines model for APIKeyList.
type APIKeyList struct {
	ApiKeys []APIKey `json:"apiKeys"`
}

// APIKeyListEnvelope defines model for APIKeyListEnvelope.
type APIKeyListEnvelope struct {
	Data  *APIKeyList `json:"data,omitempty"`
	Error *Failure    `json:"error,omitempty"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	// Action Example: jira.connected
	Action    string              `json:"action"`
	ActorType AuditEventActorType `json:"actorType"`
	CreatedAt time.Time           `json:"createdAt"`
	Id        int64               `json:"id"`

	// Metadata Context for the action. Never credential material.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Target   string                  `json:"target"`
}

// AuditEventActorType defines model for AuditEvent.ActorType.
type AuditEventActorType string

// AuditList defines model for AuditList.
type AuditList struct {
	Events []AuditEvent `json:"events"`
}

// AuditListEnvelope defines model for AuditListEnvelope.
type AuditListEnvelope struct {
	Data  *AuditList `json:"data,omitempty"`
	Error *Failure   `json:"error,omitempty"`
}

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	// Config The connector's own configuration. Its shape is whatever that
	// connector's `fields` describe -- this API does not know what a Jira
	// credential looks like.
	//
	//
	// Example: {"apiToken":"ATATT3xFfGF0...","email":"automation@your-company.com","siteUrl":"https://your-company.atlassian.net"}
	Config map[string]interface{} `json:"config"`

	// ConnectorType Example: jira
	ConnectorType string `json:"connectorType"`
}

// Connected defines model for Connected.
type Connected struct {
	ConnectorType string             `json:"connectorType"`
	Id            openapi_types.UUID `json:"id"`

	// Owner Whose credential the integration acts as. Never the credential.
	Owner struct {
		DisplayName *string `json:"displayName,omitempty"`
		Email       *string `json:"email,omitempty"`
		Id          *string `json:"id,omitempty"`
	} `json:"owner"`
}

// ConnectedEnvelope defines model for ConnectedEnvelope.
type ConnectedEnvelope struct {
	Data  *Connected `json:"data,omitempty"`
	Error *Failure   `json:"error,omitempty"`
}

// Connection defines model for Connection.
type Connection struct {
	ConnectorType string    `json:"connectorType"`
	CreatedAt     time.Time `json:"createdAt"`

	// DisplayName Whose credential this is, as the provider reports it.
	DisplayName string             `json:"displayName"`
	Id          openapi_types.UUID `json:"id"`

	// LastError Why the credential was rejected, if it was.
	LastError      nullable.Nullable[string]    `json:"lastError,omitempty"`
	LastVerifiedAt nullable.Nullable[time.Time] `json:"lastVerifiedAt,omitempty"`

	// Metadata Non-secret configuration, so a listing needs no decryption.
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Status   ConnectionStatus        `json:"status"`
}

// ConnectionStatus defines model for Connection.Status.
type ConnectionStatus string

// ConnectionList defines model for ConnectionList.
type ConnectionList struct {
	AvailableTypes []ConnectorType `json:"availableTypes"`
	Connections    []Connection    `json:"connections"`
}

// ConnectionListEnvelope defines model for ConnectionListEnvelope.
type ConnectionListEnvelope struct {
	Data  *ConnectionList `json:"data,omitempty"`
	Error *Failure        `json:"error,omitempty"`
}

// ConnectorField defines model for ConnectorField.
type ConnectorField struct {
	// Example A shape
	Example *string `json:"example,omitempty"`
	Help    *string `json:"help,omitempty"`

	// Kind How to render and validate the input. A `secret` must never be echoed
	// back: not in a response, not in a log, and not in the form after it is
	// submitted.
	Kind  FieldKind `json:"kind"`
	Label string    `json:"label"`

	// Name The key to send in the config object.
	Name     string `json:"name"`
	Required bool   `json:"required"`
}

// ConnectorType defines model for ConnectorType.
type ConnectorType struct {
	Fields []ConnectorField `json:"fields"`

	// Type Example: jira
	Type string `json:"type"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// Name Example: nightly-scanner
	Name string `json:"name"`
}

// CreateFindingRequest defines model for CreateFindingRequest.
type CreateFindingRequest struct {
	Description string    `json:"description"`
	IssueTypeId *string   `json:"issueTypeId,omitempty"`
	Labels      *[]string `json:"labels,omitempty"`

	// ProjectKey Uppercase letters, digits or underscores, starting with a letter.
	//
	// Example: NHI
	ProjectKey ProjectKey `json:"projectKey"`
	Title      string     `json:"title"`
}

// CreateTicketRequest defines model for CreateTicketRequest.
type CreateTicketRequest struct {
	Description string `json:"description"`

	// IssueTypeId Optional. A suitable type is chosen automatically.
	IssueTypeId *string `json:"issueTypeId,omitempty"`

	// ProjectKey Uppercase letters, digits or underscores, starting with a letter.
	//
	// Example: NHI
	ProjectKey ProjectKey `json:"projectKey"`
	Title      string     `json:"title"`
}

// CreatedAPIKey defines model for CreatedAPIKey.
type CreatedAPIKey struct {
	ApiKey APIKey `json:"apiKey"`
	Notice string `json:"notice"`

	// Secret The only plaintext copy. Not recoverable afterwards.
	//
	// Example: ih_a1b2c3d4e5f6_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Secret string `json:"secret"`
}

// CreatedAPIKeyEnvelope defines model for CreatedAPIKeyEnvelope.
type CreatedAPIKeyEnvelope struct {
	Data  *CreatedAPIKey `json:"data,omitempty"`
	Error *Failure       `json:"error,omitempty"`
}

// Digest defines model for Digest.
type Digest struct {
	// EveryHours How often it runs.
	EveryHours *int                         `json:"everyHours,omitempty"`
	LastRunAt  nullable.Nullable[time.Time] `json:"lastRunAt,omitempty"`
	NextRunAt  nullable.Nullable[time.Time] `json:"nextRunAt,omitempty"`
	Paused     bool                         `json:"paused"`

	// ProjectKey Where it files, when DIGEST_PROJECT_KEY names a project. Absent
	// means it resolves the first project the account can reach, at run
	// time -- so the feature works without anybody looking a key up.
	ProjectKey *string `json:"projectKey,omitempty"`

	// Scheduled False when no integration is connected: the schedule is created on
	// connect and removed on disconnect, because a digest with no
	// credential has nothing to run with.
	Scheduled bool `json:"scheduled"`
}

// DigestEnvelope defines model for DigestEnvelope.
type DigestEnvelope struct {
	Data  *Digest  `json:"data,omitempty"`
	Error *Failure `json:"error,omitempty"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error Failure `json:"error"`
}

// Failure defines model for Failure.
type Failure struct {
	// Code Stable and safe to branch on.
	Code FailureCode `json:"code"`

	// Fields The inputs to fix, keyed by field name.
	Fields *map[string]string `json:"fields,omitempty"`

	// Message Written for a person. Safe to show verbatim.
	Message string `json:"message"`
}

// FailureCode Stable and safe to branch on.
type FailureCode string

// FieldKind How to render and validate the input. A `secret` must never be echoed
// back: not in a response, not in a log, and not in the form after it is
// submitted.
type FieldKind string

// FiledTicket A ticket as a filing request answers with it: the ticket, plus whether
// this request is what created it.
//
// `created: false` means an earlier request with the same
// `Idempotency-Key` already filed it and this is that ticket. It is a
// success, not a conflict -- the caller asked for the finding to exist and
// it does. The status code says the same thing (`200` rather than `201`);
// this field says it in the body, so a client does not have to branch on
// the status to find out.
type FiledTicket struct {
	// Created Whether this request filed the ticket, or found it already filed.
	Created   bool               `json:"created"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// IssueKey Example: NHI-42
	IssueKey string `json:"issueKey"`
	IssueUrl string `json:"issueUrl"`

	// ProjectKey Uppercase letters, digits or underscores, starting with a letter.
	//
	// Example: NHI
	ProjectKey ProjectKey        `json:"projectKey"`
	Source     FiledTicketSource `json:"source"`

	// Status Live from the provider. Absent when it could not be reached.
	Status *string `json:"status,omitempty"`
	Title  string  `json:"title"`
}

// FiledTicketSource defines model for FiledTicket.Source.
type FiledTicketSource string

// FiledTicketEnvelope defines model for FiledTicketEnvelope.
type FiledTicketEnvelope struct {
	// Data A ticket as a filing request answers with it: the ticket, plus whether
	// this request is what created it.
	//
	// `created: false` means an earlier request with the same
	// `Idempotency-Key` already filed it and this is that ticket. It is a
	// success, not a conflict -- the caller asked for the finding to exist and
	// it does. The status code says the same thing (`200` rather than `201`);
	// this field says it in the body, so a client does not have to branch on
	// the status to find out.
	Data  *FiledTicket `json:"data,omitempty"`
	Error *Failure     `json:"error,omitempty"`
}

// Kind defines model for Kind.
type Kind struct {
	Id string `json:"id"`

	// Name Example: Task
	Name string `json:"name"`
}

// KindList defines model for KindList.
type KindList struct {
	IssueTypes []Kind `json:"issueTypes"`
}

// KindListEnvelope defines model for KindListEnvelope.
type KindListEnvelope struct {
	Data  *KindList `json:"data,omitempty"`
	Error *Failure  `json:"error,omitempty"`
}

// Me defines model for Me.
type Me struct {
	AccountId openapi_types.UUID `json:"accountId"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	OrgId     openapi_types.UUID `json:"orgId"`
	Roles     []MeRoles          `json:"roles"`

	// Subject The provider's stable identifier.
	Subject string `json:"subject"`
}

// MeRoles defines model for Me.Roles.
type MeRoles string

// MeEnvelope defines model for MeEnvelope.
type MeEnvelope struct {
	Data  *Me      `json:"data,omitempty"`
	Error *Failure `json:"error,omitempty"`
}

// PendingTicket defines model for PendingTicket.
type PendingTicket struct {
	Detail     string              `json:"detail"`
	Status     PendingTicketStatus `json:"status"`
	WorkflowId string              `json:"workflowId"`
}

// PendingTicketStatus defines model for PendingTicket.Status.
type PendingTicketStatus string

// PendingTicketEnvelope defines model for PendingTicketEnvelope.
type PendingTicketEnvelope struct {
	Data  *PendingTicket `json:"data,omitempty"`
	Error *Failure       `json:"error,omitempty"`
}

// ProjectKey Uppercase letters, digits or underscores, starting with a letter.
//
// Example: NHI
type ProjectKey = string

// Readiness defines model for Readiness.
type Readiness struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Ready  *bool              `json:"ready,omitempty"`
}

// SignIn defines model for SignIn.
type SignIn struct {
	// AccessToken Present it as `Authorization: Bearer <token>`.
	AccessToken string `json:"accessToken"`

	// ExpiresIn Seconds until the token expires. There is no refresh flow.
	ExpiresIn int             `json:"expiresIn"`
	TokenType SignInTokenType `json:"tokenType"`
}

// SignInTokenType defines model for SignIn.TokenType.
type SignInTokenType string

// SignInEnvelope defines model for SignInEnvelope.
type SignInEnvelope struct {
	Data  *SignIn  `json:"data,omitempty"`
	Error *Failure `json:"error,omitempty"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// StatusEnvelope defines model for StatusEnvelope.
type StatusEnvelope struct {
	Data *struct {
		// Status Example: ok
		Status *string `json:"status,omitempty"`
	} `json:"data,omitempty"`
}

// Target defines model for Target.
type Target struct {
	Id string `json:"id"`

	// Key Example: NHI
	Key  string `json:"key"`
	Name string `json:"name"`
}

// TargetList defines model for TargetList.
type TargetList struct {
	Projects []Target `json:"projects"`
}

// TargetListEnvelope defines model for TargetListEnvelope.
type TargetListEnvelope struct {
	Data  *TargetList `json:"data,omitempty"`
	Error *Failure    `json:"error,omitempty"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// IssueKey Example: NHI-42
	IssueKey string `json:"issueKey"`
	IssueUrl string `json:"issueUrl"`

	// ProjectKey Uppercase letters, digits or underscores, starting with a letter.
	//
	// Example: NHI
	ProjectKey ProjectKey   `json:"projectKey"`
	Source     TicketSource `json:"source"`

	// Status Live from the provider. Absent when it could not be reached.
	Status *string `json:"status,omitempty"`
	Title  string  `json:"title"`
}

// TicketSource defines model for Ticket.Source.
type TicketSource string

// TicketEnvelope defines model for TicketEnvelope.
type TicketEnvelope struct {
	Data  *Ticket  `json:"data,omitempty"`
	Error *Failure `json:"error,omitempty"`
}

// TicketList defines model for TicketList.
type TicketList struct {
	Tickets []Ticket `json:"tickets"`
}

// TicketListEnvelope defines model for TicketListEnvelope.
type TicketListEnvelope struct {
	Data  *TicketList `json:"data,omitempty"`
	Error *Failure    `json:"error,omitempty"`
}

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// Malformed defines model for Malformed.
type Malformed = ErrorEnvelope

// NotConnected defines model for NotConnected.
type NotConnected = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// ProviderUnavailable defines model for ProviderUnavailable.
type ProviderUnavailable = ErrorEnvelope

// QueueUnavailable defines model for QueueUnavailable.
type QueueUnavailable = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = ErrorEnvelope

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTargetsParams defines parameters for ListTargets.
type ListTargetsParams struct {
	// Query Filters by name or key.
	Query *string `form:"query,omitempty" json:"query,omitempty"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	Limit      *int        `form:"limit,omitempty" json:"limit,omitempty"`
	ProjectKey *ProjectKey `form:"projectKey,omitempty" json:"projectKey,omitempty"`
}

// CreateFindingParams defines parameters for CreateFinding.
type CreateFindingParams struct {
	// IdempotencyKey Makes a retry safe. At most 200 characters.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = SignInRequest

// ConnectJSONRequestBody defines body for Connect for application/json ContentType.
type ConnectJSONRequestBody = ConnectRequest

// CreateTicketJSONRequestBody defines body for CreateTicket for application/json ContentType.
type CreateTicketJSONRequestBody = CreateTicketRequest

// CreateFindingJSONRequestBody defines body for CreateFinding for application/json ContentType.
type CreateFindingJSONRequestBody = CreateFindingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAPIKeys This account's machine credentials
	// (GET /api/api-keys)
	ListAPIKeys(ctx echo.Context) error
	// CreateAPIKey Mint a key
	// (POST /api/api-keys)
	CreateAPIKey(ctx echo.Context) error
	// RevokeAPIKey Revoke a key
	// (DELETE /api/api-keys/{id})
	RevokeAPIKey(ctx echo.Context, id openapi_types.UUID) error
	// ListAuditEvents This account's recent security-relevant actions
	// (GET /api/audit)
	ListAuditEvents(ctx echo.Context, params ListAuditEventsParams) error
	// WhoAmI What the caller's token says about them
	// (GET /api/auth/me)
	WhoAmI(ctx echo.Context) error
	// SignIn Exchange an email address and a password for an access token
	// (POST /api/auth/signin)
	SignIn(ctx echo.Context) error
	// SignOut Stop honouring the caller's token
	// (POST /api/auth/signout)
	SignOut(ctx echo.Context) error
	// ListConnections This account's integrations, and what could be added
	// (GET /api/connections)
	ListConnections(ctx echo.Context) error
	// Connect Connect an integration
	// (POST /api/connections)
	Connect(ctx echo.Context) error
	// Disconnect Disconnect an integration
	// (DELETE /api/connections/{type})
	Disconnect(ctx echo.Context, pType string) error
	// GetDigest The recurring NHI Blog Digest for this account
	// (GET /api/digest)
	GetDigest(ctx echo.Context) error
	// RunDigest Run the digest now
	// (POST /api/digest)
	RunDigest(ctx echo.Context) error
	// ListTargets Where findings can be filed
	// (GET /api/projects)
	ListTargets(ctx echo.Context, params ListTargetsParams) error
	// ListKinds The kinds of ticket a project accepts
	// (GET /api/projects/{key}/issue-types)
	ListKinds(ctx echo.Context, key ProjectKey) error
	// ListTickets The most recent tickets this application created
	// (GET /api/tickets)
	ListTickets(ctx echo.Context, params ListTicketsParams) error
	// CreateTicket File a finding
	// (POST /api/tickets)
	CreateTicket(ctx echo.Context) error
	// GetTicket One recorded ticket
	// (GET /api/tickets/{id})
	GetTicket(ctx echo.Context, id openapi_types.UUID) error
	// CreateFinding File a finding from a scanner or a CI pipeline
	// (POST /api/v1/findings)
	CreateFinding(ctx echo.Context, params CreateFindingParams) error
	// Health Liveness
	// (GET /healthz)
	Health(ctx echo.Context) error
	// Ready Readiness
	// (GET /readyz)
	Ready(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListAPIKeys converts echo context to params.
func (w *ServerInterfaceWrapper) ListAPIKeys(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAPIKeys(ctx)
	return err
}

// CreateAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAPIKey(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAPIKey(ctx)
	return err
}

// RevokeAPIKey converts echo context to params.
func (w *ServerInterfaceWrapper) RevokeAPIKey(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RevokeAPIKey(ctx, id)
	return err
}

// ListAuditEvents converts echo context to params.
func (w *ServerInterfaceWrapper) ListAuditEvents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditEventsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListAuditEvents(ctx, params)
	return err
}

// WhoAmI converts echo context to params.
func (w *ServerInterfaceWrapper) WhoAmI(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.WhoAmI(ctx)
	return err
}

// SignIn converts echo context to params.
func (w *ServerInterfaceWrapper) SignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignIn(ctx)
	return err
}

// SignOut converts echo context to params.
func (w *ServerInterfaceWrapper) SignOut(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignOut(ctx)
	return err
}

// ListConnections converts echo context to params.
func (w *ServerInterfaceWrapper) ListConnections(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListConnections(ctx)
	return err
}

// Connect converts echo context to params.
func (w *ServerInterfaceWrapper) Connect(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Connect(ctx)
	return err
}

// Disconnect converts echo context to params.
func (w *ServerInterfaceWrapper) Disconnect(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType string

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Disconnect(ctx, pType)
	return err
}

// GetDigest converts echo context to params.
func (w *ServerInterfaceWrapper) GetDigest(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDigest(ctx)
	return err
}

// RunDigest converts echo context to params.
func (w *ServerInterfaceWrapper) RunDigest(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RunDigest(ctx)
	return err
}

// ListTargets converts echo context to params.
func (w *ServerInterfaceWrapper) ListTargets(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTargetsParams
	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", ctx.QueryParams(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter query: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTargets(ctx, params)
	return err
}

// ListKinds converts echo context to params.
func (w *ServerInterfaceWrapper) ListKinds(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key ProjectKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", ctx.Param("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListKinds(ctx, key)
	return err
}

// ListTickets converts echo context to params.
func (w *ServerInterfaceWrapper) ListTickets(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "projectKey" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "projectKey", ctx.QueryParams(), &params.ProjectKey, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectKey: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTickets(ctx, params)
	return err
}

// CreateTicket converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTicket(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTicket(ctx)
	return err
}

// GetTicket converts echo context to params.
func (w *ServerInterfaceWrapper) GetTicket(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTicket(ctx, id)
	return err
}

// CreateFinding converts echo context to params.
func (w *ServerInterfaceWrapper) CreateFinding(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateFindingParams

	headers := ctx.Request().Header
	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Idempotency-Key, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Idempotency-Key: %s", err))
		}

		params.IdempotencyKey = &IdempotencyKey
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateFinding(ctx, params)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// Ready converts echo context to params.
func (w *ServerInterfaceWrapper) Ready(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Ready(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Health, options.OperationMiddlewares["health"]...)
	router.GET(options.BaseURL+"/readyz", wrapper.Ready, options.OperationMiddlewares["ready"]...)
	router.POST(options.BaseURL+"/api/auth/signin", wrapper.SignIn, options.OperationMiddlewares["signIn"]...)
	router.GET(options.BaseURL+"/api/auth/me", wrapper.WhoAmI, options.OperationMiddlewares["whoAmI"]...)
	router.POST(options.BaseURL+"/api/auth/signout", wrapper.SignOut, options.OperationMiddlewares["signOut"]...)
	router.GET(options.BaseURL+"/api/connections", wrapper.ListConnections, options.OperationMiddlewares["listConnections"]...)
	router.POST(options.BaseURL+"/api/connections", wrapper.Connect, options.OperationMiddlewares["connect"]...)
	router.DELETE(options.BaseURL+"/api/connections/:type", wrapper.Disconnect, options.OperationMiddlewares["disconnect"]...)
	router.GET(options.BaseURL+"/api/projects", wrapper.ListTargets, options.OperationMiddlewares["listTargets"]...)
	router.GET(options.BaseURL+"/api/projects/:key/issue-types", wrapper.ListKinds, options.OperationMiddlewares["listKinds"]...)
	router.GET(options.BaseURL+"/api/tickets", wrapper.ListTickets, options.OperationMiddlewares["listTickets"]...)
	router.POST(options.BaseURL+"/api/tickets", wrapper.CreateTicket, options.OperationMiddlewares["createTicket"]...)
	router.GET(options.BaseURL+"/api/tickets/:id", wrapper.GetTicket, options.OperationMiddlewares["getTicket"]...)
	router.GET(options.BaseURL+"/api/api-keys", wrapper.ListAPIKeys, options.OperationMiddlewares["listAPIKeys"]...)
	router.POST(options.BaseURL+"/api/api-keys", wrapper.CreateAPIKey, options.OperationMiddlewares["createAPIKey"]...)
	router.DELETE(options.BaseURL+"/api/api-keys/:id", wrapper.RevokeAPIKey, options.OperationMiddlewares["revokeAPIKey"]...)
	router.GET(options.BaseURL+"/api/audit", wrapper.ListAuditEvents, options.OperationMiddlewares["listAuditEvents"]...)
	router.GET(options.BaseURL+"/api/digest", wrapper.GetDigest, options.OperationMiddlewares["getDigest"]...)
	router.POST(options.BaseURL+"/api/digest", wrapper.RunDigest, options.OperationMiddlewares["runDigest"]...)
	router.POST(options.BaseURL+"/api/v1/findings", wrapper.CreateFinding, options.OperationMiddlewares["createFinding"]...)

}
