// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: apikeys.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
insert into api_keys (org_id, account_id, key_id, secret_hash, name, scopes, created_by)
values (
    $1, $2, $3,
    $4, $5, $6, $7
)
returning id, key_id, name, scopes, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	OrgID      uuid.UUID  `json:"orgId"`
	AccountID  uuid.UUID  `json:"accountId"`
	KeyID      string     `json:"keyId"`
	SecretHash []byte     `json:"secretHash"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedBy  *uuid.UUID `json:"createdBy"`
}

type CreateAPIKeyRow struct {
	ID         uuid.UUID  `json:"id"`
	KeyID      string     `json:"keyId"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt"`
	RevokedAt  *time.Time `json:"revokedAt"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrgID,
		arg.AccountID,
		arg.KeyID,
		arg.SecretHash,
		arg.Name,
		arg.Scopes,
		arg.CreatedBy,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findAPIKey = `-- name: FindAPIKey :one
select id, org_id, account_id, secret_hash, scopes,
       (revoked_at is not null)::boolean as revoked
  from api_keys
 where key_id = $1
`

type FindAPIKeyRow struct {
	ID         uuid.UUID `json:"id"`
	OrgID      uuid.UUID `json:"orgId"`
	AccountID  uuid.UUID `json:"accountId"`
	SecretHash []byte    `json:"secretHash"`
	Scopes     []string  `json:"scopes"`
	Revoked    bool      `json:"revoked"`
}

// Resolves a tenancy from a credential, so it cannot be scoped.
func (q *Queries) FindAPIKey(ctx context.Context, keyID string) (FindAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, findAPIKey, keyID)
	var i FindAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.SecretHash,
		&i.Scopes,
		&i.Revoked,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
select id, key_id, name, scopes, created_at, last_used_at, revoked_at
  from api_keys
 where org_id = $1
   and account_id = $2
 order by created_at desc
 limit 100
`

type ListAPIKeysParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
}

type ListAPIKeysRow struct {
	ID         uuid.UUID  `json:"id"`
	KeyID      string     `json:"keyId"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt"`
	RevokedAt  *time.Time `json:"revokedAt"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.OrgID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
update api_keys
   set revoked_at = now()
 where id = $1
   and org_id = $2
   and account_id = $3
   and revoked_at is null
`

type RevokeAPIKeyParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
}

// Revocation is a timestamp rather than a delete, so audit events referencing
// the key stay resolvable.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.OrgID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
update api_keys
   set last_used_at = now()
 where id = $1
   and org_id = $2
   and account_id = $3
`

type TouchAPIKeyParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchAPIKey, arg.ID, arg.OrgID, arg.AccountID)
	return err
}
