// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const appendAuditEvent = `-- name: AppendAuditEvent :exec
insert into audit_events (org_id, account_id, actor_type, actor_id, action, target, metadata, ip)
values (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type AppendAuditEventParams struct {
	OrgID     uuid.UUID       `json:"orgId"`
	AccountID uuid.UUID       `json:"accountId"`
	ActorType string          `json:"actorType"`
	ActorID   *uuid.UUID      `json:"actorId"`
	Action    string          `json:"action"`
	Target    string          `json:"target"`
	Metadata  json.RawMessage `json:"metadata"`
	Ip        *netip.Addr     `json:"ip"`
}

// The application only ever inserts here. UPDATE and DELETE on this table are
// revoked from the application role, so the trail is append-only in the
// database as well as in this package.
func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.Exec(ctx, appendAuditEvent,
		arg.OrgID,
		arg.AccountID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Target,
		arg.Metadata,
		arg.Ip,
	)
	return err
}

const recentAuditEvents = `-- name: RecentAuditEvents :many
select id, actor_type, action, target, metadata, created_at
  from audit_events
 where org_id = $1
   and account_id = $2
 order by created_at desc
 limit $3
`

type RecentAuditEventsParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
	RowLimit  int32     `json:"rowLimit"`
}

type RecentAuditEventsRow struct {
	ID        int64           `json:"id"`
	ActorType string          `json:"actorType"`
	Action    string          `json:"action"`
	Target    string          `json:"target"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"createdAt"`
}

func (q *Queries) RecentAuditEvents(ctx context.Context, arg RecentAuditEventsParams) ([]RecentAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, recentAuditEvents, arg.OrgID, arg.AccountID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentAuditEventsRow{}
	for rows.Next() {
		var i RecentAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.Action,
			&i.Target,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
