// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: blogposts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const knownBlogURLs = `-- name: KnownBlogURLs :many
select post_url
  from blog_posts
 where org_id = $1
   and account_id = $2
   and post_url = any($3::text[])
`

type KnownBlogURLsParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
	PostUrls  []string  `json:"postUrls"`
}

// The digest re-reads the same feed daily, so this is what stops it filing a
// fresh ticket for the same post on every run.
func (q *Queries) KnownBlogURLs(ctx context.Context, arg KnownBlogURLsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, knownBlogURLs, arg.OrgID, arg.AccountID, arg.PostUrls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var post_url string
		if err := rows.Scan(&post_url); err != nil {
			return nil, err
		}
		items = append(items, post_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBlogPost = `-- name: RecordBlogPost :exec
insert into blog_posts (org_id, account_id, post_url, title, published_at, summary, ticket_id)
values (
    $1, $2, $3,
    left($4, 500), $5,
    left($6, 4000), $7
)
`

type RecordBlogPostParams struct {
	OrgID       uuid.UUID  `json:"orgId"`
	AccountID   uuid.UUID  `json:"accountId"`
	PostUrl     string     `json:"postUrl"`
	Title       string     `json:"title"`
	PublishedAt *time.Time `json:"publishedAt"`
	Summary     string     `json:"summary"`
	TicketID    *uuid.UUID `json:"ticketId"`
}

// The unique index on (org_id, account_id, post_url) is the real guarantee: a
// replayed or concurrent workflow is rejected by the database rather than by
// application ordering.
func (q *Queries) RecordBlogPost(ctx context.Context, arg RecordBlogPostParams) error {
	_, err := q.db.Exec(ctx, recordBlogPost,
		arg.OrgID,
		arg.AccountID,
		arg.PostUrl,
		arg.Title,
		arg.PublishedAt,
		arg.Summary,
		arg.TicketID,
	)
	return err
}
