// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: connections.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeConnection = `-- name: ActiveConnection :one
select id, connector_type, display_name, metadata, config_encrypted,
       status, last_verified_at, last_error, created_at
  from connections
 where org_id = $1
   and account_id = $2
   and connector_type = $3
   and status = 'active'
`

type ActiveConnectionParams struct {
	OrgID         uuid.UUID `json:"orgId"`
	AccountID     uuid.UUID `json:"accountId"`
	ConnectorType string    `json:"connectorType"`
}

type ActiveConnectionRow struct {
	ID              uuid.UUID       `json:"id"`
	ConnectorType   string          `json:"connectorType"`
	DisplayName     string          `json:"displayName"`
	Metadata        json.RawMessage `json:"metadata"`
	ConfigEncrypted []byte          `json:"configEncrypted"`
	Status          string          `json:"status"`
	LastVerifiedAt  *time.Time      `json:"lastVerifiedAt"`
	LastError       *string         `json:"lastError"`
	CreatedAt       time.Time       `json:"createdAt"`
}

// Reads the encrypted configuration, so it is used only when a credential is
// about to be needed.
func (q *Queries) ActiveConnection(ctx context.Context, arg ActiveConnectionParams) (ActiveConnectionRow, error) {
	row := q.db.QueryRow(ctx, activeConnection, arg.OrgID, arg.AccountID, arg.ConnectorType)
	var i ActiveConnectionRow
	err := row.Scan(
		&i.ID,
		&i.ConnectorType,
		&i.DisplayName,
		&i.Metadata,
		&i.ConfigEncrypted,
		&i.Status,
		&i.LastVerifiedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :one
insert into connections (
    org_id, account_id, connector_type, display_name, metadata,
    config_encrypted, status, last_verified_at, created_by
)
values (
    $1, $2, $3,
    $4, $5,
    $6,
    'active', now(), $7
)
returning id
`

type InsertConnectionParams struct {
	OrgID           uuid.UUID       `json:"orgId"`
	AccountID       uuid.UUID       `json:"accountId"`
	ConnectorType   string          `json:"connectorType"`
	DisplayName     string          `json:"displayName"`
	Metadata        json.RawMessage `json:"metadata"`
	ConfigEncrypted []byte          `json:"configEncrypted"`
	CreatedBy       *uuid.UUID      `json:"createdBy"`
}

func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertConnection,
		arg.OrgID,
		arg.AccountID,
		arg.ConnectorType,
		arg.DisplayName,
		arg.Metadata,
		arg.ConfigEncrypted,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listConnections = `-- name: ListConnections :many
select id, connector_type, display_name, metadata, status,
       last_verified_at, last_error, created_at
  from connections
 where org_id = $1
   and account_id = $2
   and status <> 'revoked'
 order by created_at desc
`

type ListConnectionsParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
}

type ListConnectionsRow struct {
	ID             uuid.UUID       `json:"id"`
	ConnectorType  string          `json:"connectorType"`
	DisplayName    string          `json:"displayName"`
	Metadata       json.RawMessage `json:"metadata"`
	Status         string          `json:"status"`
	LastVerifiedAt *time.Time      `json:"lastVerifiedAt"`
	LastError      *string         `json:"lastError"`
	CreatedAt      time.Time       `json:"createdAt"`
}

// Deliberately omits config_encrypted: nothing in a listing needs the
// credential, so it is never read into memory.
func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections, arg.OrgID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsRow{}
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorType,
			&i.DisplayName,
			&i.Metadata,
			&i.Status,
			&i.LastVerifiedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectionInvalid = `-- name: MarkConnectionInvalid :exec
update connections
   set status = 'invalid', last_error = $1, updated_at = now()
 where id = $2
   and org_id = $3
   and account_id = $4
   and status = 'active'
`

type MarkConnectionInvalidParams struct {
	LastError *string   `json:"lastError"`
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
}

func (q *Queries) MarkConnectionInvalid(ctx context.Context, arg MarkConnectionInvalidParams) error {
	_, err := q.db.Exec(ctx, markConnectionInvalid,
		arg.LastError,
		arg.ID,
		arg.OrgID,
		arg.AccountID,
	)
	return err
}

const markConnectionVerified = `-- name: MarkConnectionVerified :exec
update connections
   set last_verified_at = now(), last_error = null, updated_at = now()
 where id = $1
   and org_id = $2
   and account_id = $3
`

type MarkConnectionVerifiedParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
}

func (q *Queries) MarkConnectionVerified(ctx context.Context, arg MarkConnectionVerifiedParams) error {
	_, err := q.db.Exec(ctx, markConnectionVerified, arg.ID, arg.OrgID, arg.AccountID)
	return err
}

const revokeConnectionsOfType = `-- name: RevokeConnectionsOfType :execrows
update connections
   set status = 'revoked', updated_at = now()
 where org_id = $1
   and account_id = $2
   and connector_type = $3
   and status in ('active', 'invalid')
`

type RevokeConnectionsOfTypeParams struct {
	OrgID         uuid.UUID `json:"orgId"`
	AccountID     uuid.UUID `json:"accountId"`
	ConnectorType string    `json:"connectorType"`
}

// Revokes whatever the account currently has of this type, whether it still
// works or not. 'invalid' is included deliberately: a rejected credential is
// what a reconnect replaces, and matching only 'active' left the invalid row
// behind on every failure cycle, where the listing query returned it forever.
//
// One statement, reported. The caller that does not care about the count
// ignores it; disconnect turns a count of zero into a 404.
func (q *Queries) RevokeConnectionsOfType(ctx context.Context, arg RevokeConnectionsOfTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeConnectionsOfType, arg.OrgID, arg.AccountID, arg.ConnectorType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
