// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: idempotency.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
insert into idempotency_keys (org_id, account_id, key, request_hash)
values ($1, $2, $3, $4)
on conflict (org_id, account_id, key) do nothing
`

type ClaimIdempotencyKeyParams struct {
	OrgID       uuid.UUID `json:"orgId"`
	AccountID   uuid.UUID `json:"accountId"`
	Key         string    `json:"key"`
	RequestHash []byte    `json:"requestHash"`
}

// ON CONFLICT DO NOTHING makes the claim atomic: exactly one concurrent caller
// inserts, and the others fall through to reading the existing row.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.OrgID,
		arg.AccountID,
		arg.Key,
		arg.RequestHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
update idempotency_keys
   set ticket_id = $1
 where org_id = $2
   and account_id = $3
   and key = $4
   and ticket_id is null
`

type CompleteIdempotencyKeyParams struct {
	TicketID  *uuid.UUID `json:"ticketId"`
	OrgID     uuid.UUID  `json:"orgId"`
	AccountID uuid.UUID  `json:"accountId"`
	Key       string     `json:"key"`
}

// Attaching a result is only correct while there is not one already: a claim
// that has been taken over belongs to a different attempt now.
func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.TicketID,
		arg.OrgID,
		arg.AccountID,
		arg.Key,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
select request_hash, ticket_id, created_at
  from idempotency_keys
 where org_id = $1
   and account_id = $2
   and key = $3
`

type GetIdempotencyKeyParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
	Key       string    `json:"key"`
}

type GetIdempotencyKeyRow struct {
	RequestHash []byte     `json:"requestHash"`
	TicketID    *uuid.UUID `json:"ticketId"`
	CreatedAt   time.Time  `json:"createdAt"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.OrgID, arg.AccountID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestHash, &i.TicketID, &i.CreatedAt)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
delete from idempotency_keys
 where org_id = $1
   and account_id = $2
   and key = $3
   and ticket_id is null
`

type ReleaseIdempotencyKeyParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
	Key       string    `json:"key"`
}

// Releases a claim whose work failed, so a transient failure does not lock the
// key. A completed claim is left alone.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.OrgID, arg.AccountID, arg.Key)
	return err
}

const takeOverAbandonedIdempotencyKey = `-- name: TakeOverAbandonedIdempotencyKey :execrows
update idempotency_keys
   set created_at = now(), request_hash = $1
 where org_id = $2
   and account_id = $3
   and key = $4
   and ticket_id is null
   and created_at < now() - $5::interval
`

type TakeOverAbandonedIdempotencyKeyParams struct {
	RequestHash    []byte          `json:"requestHash"`
	OrgID          uuid.UUID       `json:"orgId"`
	AccountID      uuid.UUID       `json:"accountId"`
	Key            string          `json:"key"`
	AbandonedAfter pgtype.Interval `json:"abandonedAfter"`
}

// A claim with no result, old enough that the attempt which made it cannot
// still be running, is taken over rather than left blocking the caller.
//
// The two conditions that make a claim abandoned are here rather than in Go.
// They were in Go, above an unconditional UPDATE, which meant two callers could
// read the same stale row, both decide it was abandoned, and both take it over
// -- two tickets under one idempotency key, the exact outcome the key exists to
// prevent. As one statement the row is locked by the update itself, so the
// second caller matches nothing and the row count says so.
//
// now() is the database's clock on both sides of the comparison, so a skewed
// application clock cannot widen or narrow the window.
func (q *Queries) TakeOverAbandonedIdempotencyKey(ctx context.Context, arg TakeOverAbandonedIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeOverAbandonedIdempotencyKey,
		arg.RequestHash,
		arg.OrgID,
		arg.AccountID,
		arg.Key,
		arg.AbandonedAfter,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
