// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"orgId"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"createdAt"`
}

type ApiKey struct {
	ID         uuid.UUID  `json:"id"`
	OrgID      uuid.UUID  `json:"orgId"`
	AccountID  uuid.UUID  `json:"accountId"`
	KeyID      string     `json:"keyId"`
	SecretHash []byte     `json:"secretHash"`
	Name       string     `json:"name"`
	Scopes     []string   `json:"scopes"`
	CreatedBy  *uuid.UUID `json:"createdBy"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt"`
	RevokedAt  *time.Time `json:"revokedAt"`
}

type AuditEvent struct {
	ID        int64           `json:"id"`
	OrgID     uuid.UUID       `json:"orgId"`
	AccountID uuid.UUID       `json:"accountId"`
	ActorType string          `json:"actorType"`
	ActorID   *uuid.UUID      `json:"actorId"`
	Action    string          `json:"action"`
	Target    string          `json:"target"`
	Metadata  json.RawMessage `json:"metadata"`
	Ip        *netip.Addr     `json:"ip"`
	CreatedAt time.Time       `json:"createdAt"`
}

type BlogPost struct {
	ID          uuid.UUID  `json:"id"`
	OrgID       uuid.UUID  `json:"orgId"`
	AccountID   uuid.UUID  `json:"accountId"`
	PostUrl     string     `json:"postUrl"`
	Title       string     `json:"title"`
	PublishedAt *time.Time `json:"publishedAt"`
	Summary     string     `json:"summary"`
	TicketID    *uuid.UUID `json:"ticketId"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type Connection struct {
	ID              uuid.UUID       `json:"id"`
	OrgID           uuid.UUID       `json:"orgId"`
	AccountID       uuid.UUID       `json:"accountId"`
	ConnectorType   string          `json:"connectorType"`
	DisplayName     string          `json:"displayName"`
	Metadata        json.RawMessage `json:"metadata"`
	ConfigEncrypted []byte          `json:"configEncrypted"`
	Status          string          `json:"status"`
	LastVerifiedAt  *time.Time      `json:"lastVerifiedAt"`
	LastError       *string         `json:"lastError"`
	CreatedBy       *uuid.UUID      `json:"createdBy"`
	CreatedAt       time.Time       `json:"createdAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
}

type IdempotencyKey struct {
	OrgID       uuid.UUID  `json:"orgId"`
	AccountID   uuid.UUID  `json:"accountId"`
	Key         string     `json:"key"`
	RequestHash []byte     `json:"requestHash"`
	TicketID    *uuid.UUID `json:"ticketId"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"createdAt"`
}

type Ticket struct {
	ID            uuid.UUID  `json:"id"`
	OrgID         uuid.UUID  `json:"orgId"`
	AccountID     uuid.UUID  `json:"accountId"`
	ConnectionID  *uuid.UUID `json:"connectionId"`
	ProjectKey    string     `json:"projectKey"`
	IssueKey      string     `json:"issueKey"`
	IssueID       string     `json:"issueId"`
	IssueUrl      string     `json:"issueUrl"`
	Summary       string     `json:"summary"`
	Source        string     `json:"source"`
	CreatedByUser *uuid.UUID `json:"createdByUser"`
	CreatedByKey  *uuid.UUID `json:"createdByKey"`
	JiraCreatedAt *time.Time `json:"jiraCreatedAt"`
	CreatedAt     time.Time  `json:"createdAt"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"orgId"`
	AccountID    uuid.UUID `json:"accountId"`
	Subject      string    `json:"subject"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"displayName"`
	PasswordHash []byte    `json:"passwordHash"`
	Roles        []string  `json:"roles"`
	CreatedAt    time.Time `json:"createdAt"`
	LastSeenAt   time.Time `json:"lastSeenAt"`
}
