// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: seed.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
insert into accounts (org_id, name, slug)
values ($1, $2, $3)
returning id
`

type CreateAccountParams struct {
	OrgID uuid.UUID `json:"orgId"`
	Name  string    `json:"name"`
	Slug  string    `json:"slug"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.OrgID, arg.Name, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOrganization = `-- name: CreateOrganization :one
insert into organizations (name, slug)
values ($1, $2)
returning id
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :exec
insert into users (org_id, account_id, subject, email, display_name,
                   password_hash, roles)
values (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
`

type CreateUserParams struct {
	OrgID        uuid.UUID `json:"orgId"`
	AccountID    uuid.UUID `json:"accountId"`
	Subject      string    `json:"subject"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"displayName"`
	PasswordHash []byte    `json:"passwordHash"`
	Roles        []string  `json:"roles"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.OrgID,
		arg.AccountID,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Roles,
	)
	return err
}

const deleteOrganizationBySlug = `-- name: DeleteOrganizationBySlug :exec
delete from organizations where slug = $1
`

func (q *Queries) DeleteOrganizationBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationBySlug, slug)
	return err
}

const organizationBySlug = `-- name: OrganizationBySlug :one

select id from organizations where slug = $1
`

// Queries used only by the bootstrap step, which creates the demo tenancy.
//
// They live here with everything else rather than as hand-written SQL in the
// binary: a seed that drifts from the schema fails at first run, and finding
// that at generation time is cheaper than finding it in a reviewer's terminal.
func (q *Queries) OrganizationBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, organizationBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
