// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tickets.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertTicket = `-- name: InsertTicket :one
insert into tickets (
    org_id, account_id, connection_id, project_key, issue_key, issue_id,
    issue_url, summary, source, created_by_user, created_by_key, jira_created_at
)
values (
    $1, $2, $3,
    $4, $5, $6,
    $7, left($8, 500), $9,
    $10, $11, $12
)
returning id, org_id, account_id, connection_id, project_key, issue_key, issue_id, issue_url, summary, source, created_by_user, created_by_key, jira_created_at, created_at
`

type InsertTicketParams struct {
	OrgID         uuid.UUID  `json:"orgId"`
	AccountID     uuid.UUID  `json:"accountId"`
	ConnectionID  *uuid.UUID `json:"connectionId"`
	ProjectKey    string     `json:"projectKey"`
	IssueKey      string     `json:"issueKey"`
	IssueID       string     `json:"issueId"`
	IssueUrl      string     `json:"issueUrl"`
	Summary       string     `json:"summary"`
	Source        string     `json:"source"`
	CreatedByUser *uuid.UUID `json:"createdByUser"`
	CreatedByKey  *uuid.UUID `json:"createdByKey"`
	JiraCreatedAt *time.Time `json:"jiraCreatedAt"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, insertTicket,
		arg.OrgID,
		arg.AccountID,
		arg.ConnectionID,
		arg.ProjectKey,
		arg.IssueKey,
		arg.IssueID,
		arg.IssueUrl,
		arg.Summary,
		arg.Source,
		arg.CreatedByUser,
		arg.CreatedByKey,
		arg.JiraCreatedAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.ConnectionID,
		&i.ProjectKey,
		&i.IssueKey,
		&i.IssueID,
		&i.IssueUrl,
		&i.Summary,
		&i.Source,
		&i.CreatedByUser,
		&i.CreatedByKey,
		&i.JiraCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const recentTickets = `-- name: RecentTickets :many
select id, org_id, account_id, connection_id, project_key, issue_key, issue_id, issue_url, summary, source, created_by_user, created_by_key, jira_created_at, created_at
  from tickets
 where org_id = $1
   and account_id = $2
   and ($3::text = '' or project_key = $3::text)
 order by created_at desc
 limit $4
`

type RecentTicketsParams struct {
	OrgID      uuid.UUID `json:"orgId"`
	AccountID  uuid.UUID `json:"accountId"`
	ProjectKey string    `json:"projectKey"`
	RowLimit   int32     `json:"rowLimit"`
}

// This table, not a provider-side label, answers "created from this app": a
// label is mutable by anyone with access and cannot be trusted for it.
// An empty project_key means every project.
func (q *Queries) RecentTickets(ctx context.Context, arg RecentTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, recentTickets,
		arg.OrgID,
		arg.AccountID,
		arg.ProjectKey,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AccountID,
			&i.ConnectionID,
			&i.ProjectKey,
			&i.IssueKey,
			&i.IssueID,
			&i.IssueUrl,
			&i.Summary,
			&i.Source,
			&i.CreatedByUser,
			&i.CreatedByKey,
			&i.JiraCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketByID = `-- name: TicketByID :one
select id, org_id, account_id, connection_id, project_key, issue_key, issue_id, issue_url, summary, source, created_by_user, created_by_key, jira_created_at, created_at
  from tickets
 where org_id = $1
   and account_id = $2
   and id = $3
`

type TicketByIDParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) TicketByID(ctx context.Context, arg TicketByIDParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketByID, arg.OrgID, arg.AccountID, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.ConnectionID,
		&i.ProjectKey,
		&i.IssueKey,
		&i.IssueID,
		&i.IssueUrl,
		&i.Summary,
		&i.Source,
		&i.CreatedByUser,
		&i.CreatedByKey,
		&i.JiraCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const ticketByIssueKey = `-- name: TicketByIssueKey :one
select id, org_id, account_id, connection_id, project_key, issue_key, issue_id, issue_url, summary, source, created_by_user, created_by_key, jira_created_at, created_at
  from tickets
 where org_id = $1
   and account_id = $2
   and issue_key = $3
`

type TicketByIssueKeyParams struct {
	OrgID     uuid.UUID `json:"orgId"`
	AccountID uuid.UUID `json:"accountId"`
	IssueKey  string    `json:"issueKey"`
}

func (q *Queries) TicketByIssueKey(ctx context.Context, arg TicketByIssueKeyParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketByIssueKey, arg.OrgID, arg.AccountID, arg.IssueKey)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.ConnectionID,
		&i.ProjectKey,
		&i.IssueKey,
		&i.IssueID,
		&i.IssueUrl,
		&i.Summary,
		&i.Source,
		&i.CreatedByUser,
		&i.CreatedByKey,
		&i.JiraCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}
