// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const touchUser = `-- name: TouchUser :exec
update users set last_seen_at = now() where id = $1
`

// Records that somebody signed in. Best effort; nothing depends on it.
func (q *Queries) TouchUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUser, id)
	return err
}

const upsertUser = `-- name: UpsertUser :one

insert into users (org_id, account_id, subject, email, display_name)
values (
    $1, $2, $3,
    left($4, 320), left($5, 200)
)
on conflict (org_id, account_id, subject) do update
   set email        = excluded.email,
       display_name = excluded.display_name,
       last_seen_at = now()
returning id
`

type UpsertUserParams struct {
	OrgID       uuid.UUID `json:"orgId"`
	AccountID   uuid.UUID `json:"accountId"`
	Subject     string    `json:"subject"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
}

// Who a person is, and -- when this deployment is the one signing them in --
// what they present to prove it.
// The conflict target matches the index: same subject, same account. A subject
// seen in a different account is a different person and gets its own row, so
// org_id and account_id are not in the update -- there is nothing to move.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OrgID,
		arg.AccountID,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const userForSignIn = `-- name: UserForSignIn :one
select u.id, u.org_id, u.account_id, u.subject, u.email, u.display_name,
       u.password_hash,
       coalesce(u.roles, '{}')::text[] as roles
from users u
where lower(u.email) = lower($1)
`

type UserForSignInRow struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"orgId"`
	AccountID    uuid.UUID `json:"accountId"`
	Subject      string    `json:"subject"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"displayName"`
	PasswordHash []byte    `json:"passwordHash"`
	Roles        []string  `json:"roles"`
}

// Everything the login endpoint needs, in one read.
//
// Deliberately not scoped: a person types an email address, not an
// organization, so this is the second place in the application where a tenancy
// is discovered rather than supplied. The email index is unique across the
// table, which is what makes that safe.
//
// Roles come back with it because they are claims on the token this issues, and
// fetching them separately would mean a second round trip on the one path that
// has a person waiting.
func (q *Queries) UserForSignIn(ctx context.Context, email string) (UserForSignInRow, error) {
	row := q.db.QueryRow(ctx, userForSignIn, email)
	var i UserForSignInRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Roles,
	)
	return i, err
}
